# Generated by Django 5.1.3 on 2024-11-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=50)),
                ('session_duration', models.IntegerField(default=60)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('lockout_duration', models.IntegerField(default=15)),
                ('force_password_change', models.BooleanField(default=False)),
            ],
        ),
    ]
